apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    app: elasticsearch
spec:
  replicas: 3
  selector:
    matchLabels:
     app: elasticsearch
  template:
    metadata:
      name: elasticsearch-pod
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: registry.k8s.io/fluentd-elasticsearch:1.20