apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica-set
  namespace: cka
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
     app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx